# DESCRIPTION : Automatisation d'affichage de température sur panneau Awtrix.
# LOGIQUE : Déclenchement sur changement d'état du capteur thermique.
# SNAPSHOT : v1.0.1

alias: customapp temp_awtrix
description: "Affichage de la température sur matrice Awtrix"
triggers:
  - entity_id:
      - sensor.A_CHANGER_NOM_APPAREIL_temperature
    id: temp_awtrix
    trigger: state
conditions: []
actions:
  - variables:
      # Seuils de confort thermique configurables
      seuil_chaud: 23
      seuil_confortable: 19
      
      # Codes couleurs hexadécimaux pour le panneau matriciel
      couleur_chaud: "#8b0000"
      couleur_confortable: "#2e8b57"
      couleur_froid: "#0000ff"
      
      # Récupération de la température et formatage de l'étiquette d'affichage
      temp_value: "{{ states('sensor.A_CHANGER_NOM_APPAREIL_temperature') | float }}"
      temp_label: "{{ 'Température ' + (temp_value|round(1))|string + '°C' }}"
      
      # Calcul dynamique de la couleur du texte selon les seuils définis
      color: >
        {% if temp_value >= seuil_chaud %}
          {{ couleur_chaud }}
        {% elif temp_value >= seuil_confortable %}
          {{ couleur_confortable }}
        {% else %}
          {{ couleur_froid }}
        {% endif %}
  - action: script.awtrix_dynamique_customapp
    data:
      icone: temp_ch
      rainbow: "false"
      scrollspeed: "50"
      color: "{{ color }}"
      duree: "25"
      customapp: A_CHANGER_SLUG_APP
      message: "{{ temp_label }}"
mode: single

