# DESCRIPTION : Capteur de température composite (Moyenne ou repli).
# LOGIQUE : Calcule la moyenne de deux capteurs ou utilise le premier disponible.
# SNAPSHOT : v1.0.1

- platform: template
  sensors:
    A_CHANGER_NOM_APPAREIL_temperature:
      friendly_name: "Température A_CHANGER_NOM_HUMAIN"
      unit_of_measurement: "°C"
      unique_id: A_CHANGER_UNIQUE_ID_temperature
      value_template: >
        {# Récupération des valeurs numériques des deux sondes de référence #}
        {% set cap_1 = states('sensor.A_CHANGER_CAPTEUR_1_temperature') | float(0) %}
        {% set cap_2 = states('sensor.A_CHANGER_CAPTEUR_2_temperature') | float(0) %}
        
        {# Logique de calcul : Priorité à la moyenne si les deux sondes sont actives (>0) #}
        {% if cap_1 > 0 and cap_2 > 0 %}
          {{ ((cap_1 + cap_2) / 2) | round(2) }}
        {# Sinon, repli sur la sonde disponible (cap_1) #}
        {% elif cap_1 > 0 %}
          {{ cap_1 | round(2) }}
        {# Ou repli sur la sonde secondaire (cap_2) #}
        {% elif cap_2 > 0 %}
          {{ cap_2 | round(2) }}
        {# Cas critique : aucune sonde disponible #}
        {% else %}
          {{ 'unavailable' }}
        {% endif %}
      device_class: temperature

